### PR TITLE
update and audit JS packages

### PR DESCRIPTION
**Pull request by MalcolmAG**
I updated the packages for React and MaterialUI. Changes should be clear from package.json

### CODE REVIEW

**Review by tmclean15 — COMMENTED** [review]
All looks good.

**Comment by ghost** [comment]
Could you write a line or two for those less familiar with these packages why this is necessary at this stage, the purpose of the issue. You mentioned it in slack, so copy those thoughts here.

**Comment by MalcolmAG** [comment]
> Could you write a line or two for those less familiar with these packages why this is necessary at this stage, the purpose of the issue. You mentioned it in slack, so copy those thoughts here.
@rice-cake 
I'll go over the dependencies in the package.json. The packages in package-lock.json are the dependencies of the dependencies (which we should leave be).

"@material-ui/core": "^4.9.14" - material-ui for styling
"package.json": "^2.0.1" - managing the package.json
"react": "^16.13.1" - user interface lib react
"react-dom": "^16.13.1" - lets react manipulate the DOM
"react-router-dom": "^5.2.0" - lets react manage DOM through the routes (useful for a SPA) 
"react-scripts": "^3.4.1" - scripts for running react

I'm updating to the latest versions to get access to the latest features and to fix vulnerabilities and bugs present in past versions. Unless we have a reason not to, we should try to update.

**Review by ghost — APPROVED** [review]
I'm assuming that you've run this and it works fine.

**Pull request merged**
